### ISSUE TITLE
feat: 모달 컴포넌트

### ISSUE THREAD

**Issue by 100Gyeon** [sopt-makers/sopt-web-product#20]
## ✨ Description
신청자 리스트 페이지, 모임 상세 페이지에서 공통으로 사용할 모달 컴포넌트 구현
![image](https://user-images.githubusercontent.com/58380158/198819078-1a1eb5c9-ffd9-45dc-a9e7-7db12d83c6de.png)

## ✅ To Do List
- [x] 모달 컴포넌트 구현
- [x] 신청자 리스트 페이지에 적용
  - `신청내역 상세` 버튼 클릭 시 '신청내역 상세 보기' 모달 띄우기
- [x] 모임 상세 페이지에 적용
  - `신청하기` 버튼 클릭 시 '모임 신청하기' 모달 띄우기
  - `모집 현황` 버튼 클릭 시 '신청자 리스트' 모달 띄우기
  - `삭제` 버튼 클릭 시 삭제 경고 모달 띄우기

**Comment by na-reum** [comment]
fontAg: '24_bold_100',이 적용 안 되는 것 같은데 빼먹은 부분이 있는지 한 번 봐주시면 감사하겠습니다.

이부분에 대해서, util들이 가끔 안먹히는 상황이 있는것 같은데, 어떤 부분에서 안되는지 파악하기가 어려워서, 일단 안되면 풀어서 사용하는걸 추천해
